import { AITagGenerationPort } from '../ports/AITagGenerationPort';
import { TagService } from '@/domain/tags/services/TagService';
import { SupabaseClient } from '@supabase/supabase-js';

/**
 * Use Case: Générer des tags automatiquement via IA pour un lien
 * Application Layer - Orchestre la génération de tags et leur association
 */

export interface GenerateAITagsInput {
  linkId: string;
  userId: string;
  imageUrl: string;
  linkUrl?: string;
  linkTitle?: string;
  linkDescription?: string;
  replaceExisting?: boolean; // Si true, remplace les tags AI existants
}

export interface GenerateAITagsOutput {
  tags: string[];
  created: string[]; // Tags créés
  existing: string[]; // Tags déjà existants
  linked: string[]; // Tags liés avec succès
  success: boolean;
}

export class GenerateAITagsUseCase {
  constructor(
    private readonly aiService: AITagGenerationPort,
    private readonly tagService: TagService,
    private readonly supabase: SupabaseClient
  ) {}

  async execute(input: GenerateAITagsInput): Promise<GenerateAITagsOutput> {
    // 1. Vérifier que le lien existe et appartient à l'utilisateur
    const { data: link, error: linkError } = await this.supabase
      .from('links')
      .select('id, user_id')
      .eq('id', input.linkId)
      .single();

    if (linkError || !link) {
      throw new Error('Link not found');
    }

    if (link.user_id !== input.userId) {
      throw new Error('Unauthorized: Link does not belong to user');
    }

    // 2. Générer les tags via l'IA
    const aiResult = await this.aiService.generateTagsFromImage({
      imageUrl: input.imageUrl,
      linkUrl: input.linkUrl,
      linkTitle: input.linkTitle,
      linkDescription: input.linkDescription,
    });

    // 3. Si replaceExisting, supprimer les anciens tags auto-générés
    if (input.replaceExisting) {
      await this.removeAutoGeneratedTags(input.linkId);
    }

    // 4. Créer ou récupérer les tags et les associer au lien
    const created: string[] = [];
    const existing: string[] = [];
    const linked: string[] = [];

    for (const tagName of aiResult.tags) {
      try {
        // Vérifier si le tag existe déjà avant de créer
        const existingTag = await this.tagService.getTagByName(input.userId, tagName);

        if (existingTag) {
          existing.push(tagName);
        }

        // Créer ou récupérer le tag (avec normalisation)
        const tag = await this.tagService.createTag(input.userId, tagName);

        if (!tag) {
          console.warn(`[GenerateAITags] Failed to create tag: ${tagName}`);
          continue;
        }

        // Si le tag n'existait pas avant, il a été créé
        if (!existingTag) {
          created.push(tagName);
        }

        // Vérifier si l'association existe déjà
        const { data: existingLinkTag } = await this.supabase
          .from('link_tags')
          .select('id')
          .eq('link_id', input.linkId)
          .eq('tag_id', tag.id)
          .maybeSingle();

        // Associer le tag au lien avec is_auto_generated=true si pas déjà lié
        if (!existingLinkTag) {
          const { error: linkTagError } = await this.supabase
            .from('link_tags')
            .insert({
              link_id: input.linkId,
              tag_id: tag.id,
              is_auto_generated: true,
            });

          if (linkTagError) {
            console.warn(`[GenerateAITags] Failed to link tag: ${tagName}`, linkTagError);
            continue;
          }
        }

        linked.push(tagName);
      } catch (error) {
        console.warn(`[GenerateAITags] Error processing tag: ${tagName}`, error);
      }
    }

    return {
      tags: aiResult.tags,
      created,
      existing,
      linked,
      success: true,
    };
  }

  /**
   * Supprime les tags auto-générés d'un lien
   */
  private async removeAutoGeneratedTags(linkId: string): Promise<void> {
    await this.supabase
      .from('link_tags')
      .delete()
      .eq('link_id', linkId)
      .eq('is_auto_generated', true);
  }
}
