| sql                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| ALTER TABLE public.folders ENABLE ROW LEVEL SECURITY;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| ALTER TABLE public.link_tags ENABLE ROW LEVEL SECURITY;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| ALTER TABLE public.links ENABLE ROW LEVEL SECURITY;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| ALTER TABLE public.share_access ENABLE ROW LEVEL SECURITY;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| ALTER TABLE public.shares ENABLE ROW LEVEL SECURITY;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| CREATE POLICY "Enable insert during signup" ON public.users AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((( SELECT auth.uid() AS uid) = id));                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| CREATE POLICY "Users can create links in own or editable shared folders" ON public.links AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (((auth.uid() = user_id) OR (EXISTS ( SELECT 1
   FROM (shares
     JOIN folders ON ((folders.id = shares.folder_id)))
  WHERE ((shares.folder_id = links.folder_id) AND (folders.is_group = false) AND (shares.is_active = true) AND (shares.permission = 'edit'::text) AND ((shares.expires_at IS NULL) OR (shares.expires_at > now())) AND ((shares.share_token IS NOT NULL) OR (shares.shared_with_email = (auth.jwt() ->> 'email'::text))))))));       |
| CREATE POLICY "Users can create shares for themselves via public links" ON public.shares AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (((shared_with_email = (auth.jwt() ->> 'email'::text)) AND (share_token IS NULL)));                                                                                                                                                                                                                                                                                                                                                                         |
| CREATE POLICY "Users can create shares" ON public.shares AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((( SELECT auth.uid() AS uid) = shared_by));                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| CREATE POLICY "Users can create their own folders or in shared groups" ON public.folders AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (((auth.uid() = user_id) OR (parent_folder_id IS NOT NULL)));                                                                                                                                                                                                                                                                                                                                                                                               |
| CREATE POLICY "Users can create their own tags" ON public.tags AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| CREATE POLICY "Users can delete their own folders" ON public.folders AS PERMISSIVE FOR DELETE TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id));                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| CREATE POLICY "Users can delete their own links or editable shared links" ON public.links AS PERMISSIVE FOR DELETE TO authenticated USING (((auth.uid() = user_id) OR (EXISTS ( SELECT 1
   FROM (shares
     JOIN folders ON ((folders.id = shares.folder_id)))
  WHERE ((shares.folder_id = links.folder_id) AND (folders.is_group = false) AND (shares.is_active = true) AND (shares.permission = 'edit'::text) AND ((shares.expires_at IS NULL) OR (shares.expires_at > now())) AND ((shares.share_token IS NOT NULL) OR (shares.shared_with_email = (auth.jwt() ->> 'email'::text))))))));           |
| CREATE POLICY "Users can delete their own tags" ON public.tags AS PERMISSIVE FOR DELETE TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id));                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| CREATE POLICY "Users can delete their shares" ON public.shares AS PERMISSIVE FOR DELETE TO authenticated USING ((( SELECT auth.uid() AS uid) = shared_by));                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| CREATE POLICY "Users can manage their link tags or editable shared link tags" ON public.link_tags AS PERMISSIVE FOR ALL TO authenticated USING ((EXISTS ( SELECT 1
   FROM links l
  WHERE ((l.id = link_tags.link_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR (EXISTS ( SELECT 1
           FROM shares s
          WHERE ((s.folder_id = l.folder_id) AND (s.is_active = true) AND (s.permission = 'edit'::text) AND ((s.expires_at IS NULL) OR (s.expires_at > now())) AND ((s.share_token IS NOT NULL) OR (s.shared_with_email = (( SELECT auth.jwt() AS jwt) ->> 'email'::text))))))))))); |
| CREATE POLICY "Users can revoke shares they received" ON public.shares AS PERMISSIVE FOR UPDATE TO public USING ((shared_with_email = (auth.jwt() ->> 'email'::text))) WITH CHECK (((shared_with_email = (auth.jwt() ->> 'email'::text)) AND (is_active = false)));                                                                                                                                                                                                                                                                                                                                       |
| CREATE POLICY "Users can update own profile" ON public.users AS PERMISSIVE FOR UPDATE TO authenticated USING ((( SELECT auth.uid() AS uid) = id)) WITH CHECK ((( SELECT auth.uid() AS uid) = id));                                                                                                                                                                                                                                                                                                                                                                                                        |
| CREATE POLICY "Users can update their own folders or shared folders with edit " ON public.folders AS PERMISSIVE FOR UPDATE TO authenticated USING (((auth.uid() = user_id) OR (EXISTS ( SELECT 1
   FROM shares
  WHERE ((shares.folder_id = folders.id) AND (shares.is_active = true) AND (shares.permission = 'edit'::text) AND ((shares.expires_at IS NULL) OR (shares.expires_at > now())) AND ((shares.share_token IS NOT NULL) OR (shares.shared_with_email = ( SELECT (auth.jwt() ->> 'email'::text)))))))));                                                                                      |
| CREATE POLICY "Users can update their own links or editable shared links" ON public.links AS PERMISSIVE FOR UPDATE TO authenticated USING (((auth.uid() = user_id) OR (EXISTS ( SELECT 1
   FROM (shares
     JOIN folders ON ((folders.id = shares.folder_id)))
  WHERE ((shares.folder_id = links.folder_id) AND (folders.is_group = false) AND (shares.is_active = true) AND (shares.permission = 'edit'::text) AND ((shares.expires_at IS NULL) OR (shares.expires_at > now())) AND ((shares.share_token IS NOT NULL) OR (shares.shared_with_email = (auth.jwt() ->> 'email'::text))))))));           |
| CREATE POLICY "Users can update their shares" ON public.shares AS PERMISSIVE FOR UPDATE TO authenticated USING ((( SELECT auth.uid() AS uid) = shared_by));                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| CREATE POLICY "Users can view profiles" ON public.users AS PERMISSIVE FOR SELECT TO authenticated USING (((id = auth.uid()) OR (EXISTS ( SELECT 1
   FROM shares s
  WHERE ((s.shared_by = users.id) AND (s.shared_with_email = (auth.jwt() ->> 'email'::text)) AND (s.is_active = true)))) OR (EXISTS ( SELECT 1
   FROM (shares s
     JOIN folders f ON ((s.folder_id = f.id)))
  WHERE ((f.user_id = users.id) AND (s.shared_with_email = (auth.jwt() ->> 'email'::text)) AND (s.is_active = true))))));                                                                                              |
| CREATE POLICY "Users can view public shares" ON public.shares AS PERMISSIVE FOR SELECT TO authenticated USING (((shared_with_email IS NULL) AND (is_active = true) AND ((expires_at IS NULL) OR (expires_at > now()))));                                                                                                                                                                                                                                                                                                                                                                                  |
| CREATE POLICY "Users can view share access for their shares" ON public.share_access AS PERMISSIVE FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1
   FROM shares
  WHERE ((shares.id = share_access.share_id) AND (shares.shared_by = ( SELECT auth.uid() AS uid))))));                                                                                                                                                                                                                                                                                                                             |
| CREATE POLICY "Users can view shares shared with them" ON public.shares AS PERMISSIVE FOR SELECT TO authenticated USING ((shared_with_email = (auth.jwt() ->> 'email'::text)));                                                                                                                                                                                                                                                                                                                                                                                                                           |
| CREATE POLICY "Users can view shares they created" ON public.shares AS PERMISSIVE FOR SELECT TO authenticated USING ((( SELECT auth.uid() AS uid) = shared_by));                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| CREATE POLICY "Users can view their own folders or shared folders" ON public.folders AS PERMISSIVE FOR SELECT TO authenticated USING (((( SELECT auth.uid() AS uid) = user_id) OR (EXISTS ( SELECT 1
   FROM shares
  WHERE ((shares.folder_id = folders.id) AND (shares.is_active = true) AND ((shares.expires_at IS NULL) OR (shares.expires_at > now())) AND ((shares.share_token IS NOT NULL) OR (shares.shared_with_email = (( SELECT auth.jwt() AS jwt) ->> 'email'::text))))))));                                                                                                                  |
| CREATE POLICY "Users can view their own links or shared links" ON public.links AS PERMISSIVE FOR SELECT TO authenticated USING (((( SELECT auth.uid() AS uid) = user_id) OR (EXISTS ( SELECT 1
   FROM shares
  WHERE ((shares.folder_id = links.folder_id) AND (shares.is_active = true) AND ((shares.expires_at IS NULL) OR (shares.expires_at > now())) AND ((shares.share_token IS NOT NULL) OR (shares.shared_with_email = (( SELECT auth.jwt() AS jwt) ->> 'email'::text))))))));                                                                                                                   |
| CREATE POLICY "Users can view their own tags or shared tags" ON public.tags AS PERMISSIVE FOR SELECT TO authenticated USING (((( SELECT auth.uid() AS uid) = user_id) OR (EXISTS ( SELECT 1
   FROM ((link_tags lt
     JOIN links l ON ((lt.link_id = l.id)))
     JOIN shares s ON ((s.folder_id = l.folder_id)))
  WHERE ((lt.tag_id = tags.id) AND (s.is_active = true) AND ((s.expires_at IS NULL) OR (s.expires_at > now())) AND ((s.share_token IS NOT NULL) OR (s.shared_with_email = (( SELECT auth.jwt() AS jwt) ->> 'email'::text))))))));                                                     |